kind = "mobile"
previewPath = "/"
title = "Juanfe & Yukita Home"
version = "1.0.0"
id = "artifacts/home-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 21136

[services.development]
run = "pnpm --filter @workspace/home-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/home-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/home-app", "run", "serve" ]

[services.env]
PORT = "21136"
BASE_PATH = "/"
